export const NATY_TOKEN_ABI = [
  "constructor(address initialOwner)",
  "error ECDSAInvalidSignature()",
  "error ECDSAInvalidSignatureLength(uint256 length)",
  "error ECDSAInvalidSignatureS(bytes32 s)",
  "error ERC20InsufficientAllowance(address spender, uint256 allowance, uint256 needed)",
  "error ERC20InsufficientBalance(address sender, uint256 balance, uint256 needed)",
  "error ERC20InvalidApprover(address approver)",
  "error ERC20InvalidReceiver(address receiver)",
  "error ERC20InvalidSender(address sender)",
  "error ERC20InvalidSpender(address spender)",
  "error ERC2612ExpiredSignature(uint256 deadline)",
  "error ERC2612InvalidSigner(address signer, address owner)",
  "error InvalidAccountNonce(address account, uint256 currentNonce)",
  "error InvalidShortString()",
  "error OwnableInvalidOwner(address owner)",
  "error OwnableUnauthorizedAccount(address account)",
  "error StringTooLong(string str)",
  "event Approval(address indexed owner, address indexed spender, uint256 value)",
  "event EIP712DomainChanged()",
  "event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)",
  "event Transfer(address indexed from, address indexed to, uint256 value)",
  "function DOMAIN_SEPARATOR() view returns (bytes32)",
  "function allowance(address owner, address spender) view returns (uint256)",
  "function approve(address spender, uint256 value) returns (bool)",
  "function balanceOf(address account) view returns (uint256)",
  "function burn(uint256 value)",
  "function burnFrom(address account, uint256 value)",
  "function decimals() view returns (uint8)",
  "function eip712Domain() view returns (bytes1 fields, string name, string version, uint256 chainId, address verifyingContract, bytes32 salt, uint256[] extensions)",
  "function mint(address to, uint256 amount)",
  "function name() view returns (string)",
  "function nonces(address owner) view returns (uint256)",
  "function owner() view returns (address)",
  "function permit(address owner, address spender, uint256 value, uint256 deadline, uint8 v, bytes32 r, bytes32 s)",
  "function renounceOwnership()",
  "function symbol() view returns (string)",
  "function totalSupply() view returns (uint256)",
  "function transfer(address to, uint256 value) returns (bool)",
  "function transferFrom(address from, address to, uint256 value) returns (bool)",
  "function transferOwnership(address newOwner)"
];

export const NATY_NFT_ABI = [
  "constructor(address initialOwner)",
  "error ERC721IncorrectOwner(address sender, uint256 tokenId, address owner)",
  "error ERC721InsufficientApproval(address operator, uint256 tokenId)",
  "error ERC721InvalidApprover(address approver)",
  "error ERC721InvalidOperator(address operator)",
  "error ERC721InvalidOwner(address owner)",
  "error ERC721InvalidReceiver(address receiver)",
  "error ERC721InvalidSender(address sender)",
  "error ERC721NonexistentToken(uint256 tokenId)",
  "error OwnableInvalidOwner(address owner)",
  "error OwnableUnauthorizedAccount(address account)",
  "event Approval(address indexed owner, address indexed approved, uint256 indexed tokenId)",
  "event ApprovalForAll(address indexed owner, address indexed operator, bool approved)",
  "event BatchMetadataUpdate(uint256 _fromTokenId, uint256 _toTokenId)",
  "event MetadataUpdate(uint256 _tokenId)",
  "event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)",
  "event Transfer(address indexed from, address indexed to, uint256 indexed tokenId)",
  "function approve(address to, uint256 tokenId)",
  "function balanceOf(address owner) view returns (uint256)",
  "function getApproved(uint256 tokenId) view returns (address)",
  "function isApprovedForAll(address owner, address operator) view returns (bool)",
  "function name() view returns (string)",
  "function owner() view returns (address)",
  "function ownerOf(uint256 tokenId) view returns (address)",
  "function renounceOwnership()",
  "function safeMint(address to, string uri)",
  "function safeTransferFrom(address from, address to, uint256 tokenId)",
  "function safeTransferFrom(address from, address to, uint256 tokenId, bytes data)",
  "function setApprovalForAll(address operator, bool approved)",
  "function supportsInterface(bytes4 interfaceId) view returns (bool)",
  "function symbol() view returns (string)",
  "function tokenURI(uint256 tokenId) view returns (string)",
  "function transferFrom(address from, address to, uint256 tokenId)",
  "function transferOwnership(address newOwner)"
];

export const NATY_STAKING_ABI = [
  "constructor(address _stakingToken, address _rewardToken, address _priceFeed, address _initialOwner)",
  "error OwnableInvalidOwner(address owner)",
  "error OwnableUnauthorizedAccount(address account)",
  "error ReentrancyGuardReentrantCall()",
  "event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)",
  "event RewardPaid(address indexed user, uint256 reward)",
  "event Staked(address indexed user, uint256 amount)",
  "event Withdrawn(address indexed user, uint256 amount)",
  "function balanceOf(address account) view returns (uint256)",
  "function earned(address account) view returns (uint256)",
  "function getLatestPrice() view returns (int256)",
  "function getReward()",
  "function lastUpdateTime() view returns (uint256)",
  "function owner() view returns (address)",
  "function renounceOwnership()",
  "function rewardPerToken() view returns (uint256)",
  "function rewardPerTokenStored() view returns (uint256)",
  "function rewardRate() view returns (uint256)",
  "function rewardToken() view returns (address)",
  "function rewards(address) view returns (uint256)",
  "function stake(uint256 amount)",
  "function stakingToken() view returns (address)",
  "function totalSupply() view returns (uint256)",
  "function transferOwnership(address newOwner)",
  "function userRewardPerTokenPaid(address) view returns (uint256)",
  "function withdraw(uint256 amount)"
];

export const NATY_DAO_ABI = [
  "constructor(address _stakingContract, address _initialOwner)",
  "error OwnableInvalidOwner(address owner)",
  "error OwnableUnauthorizedAccount(address account)",
  "event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)",
  "event ProposalCreated(uint256 proposalId, string description)",
  "event Voted(uint256 proposalId, address voter, uint256 weight)",
  "function createProposal(string description)",
  "function getProposalCount() view returns (uint256)",
  "function owner() view returns (address)",
  "function proposals(uint256) view returns (string description, uint256 voteCount, bool executed)",
  "function renounceOwnership()",
  "function stakingContract() view returns (address)",
  "function transferOwnership(address newOwner)",
  "function vote(uint256 proposalId)"
];
